UPDATE lab1DB.Trees SET title = 'updatedTreed', author = 'authorf' WHERE id = 1;
UPDATE lab1DB.Trees SET title = 'qw', author = 'qwe' WHERE id = 22;
UPDATE lab1DB.Trees SET title = 'qw', author = null WHERE id = 23;
UPDATE lab1DB.Trees SET title = 'qw1111', author = 'qwe1111' WHERE id = 26;
UPDATE lab1DB.Trees SET title = 'qw1111', author = 'qwe1111' WHERE id = 27;
UPDATE lab1DB.Trees SET title = 'qw1111', author = 'qwe1111' WHERE id = 28;
UPDATE lab1DB.Trees SET title = 'q', author = 'q' WHERE id = 29;
UPDATE lab1DB.Trees SET title = 'superTree', author = null WHERE id = 30;
UPDATE lab1DB.Trees SET title = 'title', author = 'author' WHERE id = 31;
UPDATE lab1DB.Trees SET title = 'superTree', author = null WHERE id = 32;
UPDATE lab1DB.Trees SET title = 'superTree', author = null WHERE id = 33;
UPDATE lab1DB.Trees SET title = 'super', author = 'puper' WHERE id = 34;
UPDATE lab1DB.Trees SET title = 'title', author = 'author' WHERE id = 35;
UPDATE lab1DB.Trees SET title = 'new tree', author = 'new authordsa' WHERE id = 71;